[package]
name = "swym-rbtree"
version = "0.1.0"
authors = ["tyler <tyler@brainiumstudios.com>"]
edition = "2018"

[features]
stats = ["swym/stats"]

[dependencies]
swym = { path = "../" }

[dev-dependencies]
crossbeam-utils = "0.6.5"
jemallocator = "0.1.9"
rand = "0.6.5"